import earthieAvatarUrl from '../assets/logo@4x.png'

export const PACK_DELAYS = {
  1: 4000,
  2: 6000,
  3: 8000,
}

export const COMMUNITY_POSTS = [
  {
    id: 'garden-water-saved',
    username: 'ليان',
    usernameEn: 'Layan',
    text: 'سقينا حديقة المدرسة بمياه معاد استخدامها اليوم. الفريق كله شارك!',
    textEn: 'We watered the school garden with recycled water today. The whole team helped!',
    likes: 128,
    comments: 18,
    avatar: earthieAvatarUrl,
    icon: '💧',
    iconBg: '#74cbd5',
    position: { top: '7%', left: '5%' },
    rotation: -5,
    layer: 'back',
    packId: 1,
    density: 'tablet',
  },
  {
    id: 'tree-challenge-started',
    username: 'عمر',
    usernameEn: 'Omar',
    text: 'بدأنا تحدي زراعة 20 شتلة في الحي. من يريد الانضمام؟',
    textEn: 'We started a challenge to plant 20 seedlings in the neighborhood. Who wants to join?',
    likes: 92,
    comments: 11,
    avatar: earthieAvatarUrl,
    icon: '🌱',
    iconBg: '#4d2d78',
    position: { top: '12%', left: '42%' },
    rotation: 4,
    layer: 'back',
    packId: 2,
    density: 'tablet',
  },
  {
    id: 'cleanup-progress',
    username: 'سارة',
    usernameEn: 'Sara',
    text: 'نظفنا جزء من الشاطئ وجمعنا 14 كيس نفايات. فخورين فيكم!',
    textEn: 'We cleaned part of the beach and collected 14 bags of trash. Proud of you all!',
    likes: 176,
    comments: 27,
    avatar: earthieAvatarUrl,
    icon: '♻️',
    iconBg: '#e9a26d',
    position: { top: '8%', right: '7%' },
    rotation: 6,
    layer: 'back',
    packId: 3,
    density: 'tablet',
  },
  {
    id: 'bike-to-school',
    username: 'يزن',
    usernameEn: 'Yazan',
    text: 'رحت على المدرسة بالدراجة بدل السيارة. 3 أيام متتالية!',
    textEn: 'I biked to school instead of taking the car. 3 days in a row!',
    likes: 77,
    comments: 9,
    avatar: earthieAvatarUrl,
    icon: '🚲',
    iconBg: '#e96c8f',
    position: { top: '37%', left: '2%' },
    rotation: 3,
    layer: 'back',
    packId: 2,
    density: 'desktop',
  },
  {
    id: 'recycling-bin-alert',
    username: 'نور',
    usernameEn: 'Nour',
    text: 'في حاوية تدوير جديدة جنب النادي. خلونا نستخدمها صح.',
    textEn: "There's a new recycling bin near the club. Let's use it right.",
    likes: 61,
    comments: 7,
    avatar: earthieAvatarUrl,
    icon: '🗑️',
    iconBg: '#e9a26d',
    position: { top: '48%', left: '44%' },
    rotation: -4,
    layer: 'back',
    packId: 1,
    density: 'mobile',
  },
  {
    id: 'solar-roof-win',
    username: 'مالك',
    usernameEn: 'Malek',
    text: 'ركبنا ألواح شمسية صغيرة للنادي البيئي. أول نتيجة: إضاءة الحديقة!',
    textEn: 'We installed small solar panels for the eco club. First result: lighting the garden!',
    likes: 143,
    comments: 20,
    avatar: earthieAvatarUrl,
    icon: '☀️',
    iconBg: '#f6c85f',
    position: { bottom: '9%', right: '6%' },
    rotation: -6,
    layer: 'back',
    packId: 3,
    density: 'desktop',
  },
  {
    id: 'plant-swap',
    username: 'جنى',
    usernameEn: 'Jana',
    text: 'تبادلنا نباتات بدل شراء جديد. عندي ريحان زيادة إذا حدا بده.',
    textEn: 'We swapped plants instead of buying new ones. I have extra basil if anyone wants some.',
    likes: 84,
    comments: 13,
    avatar: earthieAvatarUrl,
    icon: '🪴',
    iconBg: '#4d2d78',
    position: { bottom: '8%', left: '18%' },
    rotation: 5,
    layer: 'back',
    packId: 1,
    density: 'tablet',
  },
  {
    id: 'air-quality-report',
    username: 'آدم',
    usernameEn: 'Adam',
    text: 'بلغنا عن دخان كثيف قرب الملعب. صحة الأطفال أهم.',
    textEn: "We reported heavy smoke near the field. Children's health comes first.",
    likes: 109,
    comments: 16,
    avatar: earthieAvatarUrl,
    icon: '🌬️',
    iconBg: '#9de1dd',
    position: { top: '40%', right: '15%' },
    rotation: 3,
    layer: 'back',
    packId: 2,
    density: 'desktop',
  },
  {
    id: 'seed-bank',
    username: 'هند',
    usernameEn: 'Hind',
    text: 'فتحنا صندوق بذور صغير في الحي. كل واحد يأخذ بذور ويترك بذور.',
    textEn: 'We opened a small seed bank in the neighborhood. Everyone takes seeds and leaves seeds.',
    likes: 73,
    comments: 8,
    avatar: earthieAvatarUrl,
    icon: '🌾',
    iconBg: '#f6c85f',
    position: { top: '22%', left: '15%' },
    rotation: 6,
    layer: 'back',
    packId: 1,
    density: 'desktop',
  },
  {
    id: 'school-points',
    username: 'سليم',
    usernameEn: 'Salim',
    text: 'صفنا جمع 420 نقطة من تحديات الأسبوع. المنافسة حماس!',
    textEn: "Our class collected 420 points from this week's challenges. The competition is on!",
    likes: 132,
    comments: 21,
    avatar: earthieAvatarUrl,
    icon: '⭐',
    iconBg: '#f6c85f',
    position: { top: '58%', right: '36%' },
    rotation: -3,
    layer: 'back',
    packId: 3,
    density: 'desktop',
  },
  {
    id: 'reuse-jars',
    username: 'فرح',
    usernameEn: 'Farah',
    text: 'حوّلنا المرطبانات القديمة لأصص نباتات صغيرة للمطبخ.',
    textEn: 'We turned old jars into small plant pots for the kitchen.',
    likes: 58,
    comments: 5,
    avatar: earthieAvatarUrl,
    icon: '🫙',
    iconBg: '#bfa7ee',
    position: { bottom: '3%', left: '41%' },
    rotation: 2,
    layer: 'back',
    packId: 2,
    density: 'tablet',
  },
  {
    id: 'lights-off',
    username: 'راشد',
    usernameEn: 'Rashed',
    text: 'اتفقنا نطفّي أضواء الصف وقت الاستراحة. عادة بسيطة وفرق واضح.',
    textEn: 'We agreed to turn off classroom lights during break. A small habit, a big difference.',
    likes: 88,
    comments: 10,
    avatar: earthieAvatarUrl,
    icon: '💡',
    iconBg: '#f6c85f',
    position: { top: '4%', left: '66%' },
    rotation: -5,
    layer: 'back',
    packId: 3,
    density: 'desktop',
  },
  {
    id: 'front-compost',
    username: 'تالا',
    usernameEn: 'Tala',
    text: 'صندوق السماد في البيت صار يعطي تربة ممتازة للنباتات.',
    textEn: 'The home compost bin is now producing excellent soil for the plants.',
    likes: 68,
    comments: 6,
    avatar: earthieAvatarUrl,
    icon: '🍃',
    iconBg: '#4d2d78',
    position: { top: '22%', left: '30%' },
    rotation: -3,
    layer: 'front',
    packId: 3,
    density: 'tablet',
  },
  {
    id: 'front-group-photo',
    username: 'لمى',
    usernameEn: 'Lama',
    text: 'نزلنا صورة قبل وبعد تنظيف الساحة. الفرق يفتح النفس.',
    textEn: 'We posted a before-and-after photo of cleaning the yard. The difference is amazing.',
    likes: 147,
    comments: 22,
    avatar: earthieAvatarUrl,
    icon: '📸',
    iconBg: '#bfa7ee',
    position: { top: '14%', right: '40%' },
    rotation: -4,
    layer: 'front',
    packId: 2,
    density: 'desktop',
  },
  {
    id: 'front-bottle-count',
    username: 'كريم',
    usernameEn: 'Kareem',
    text: 'جمعنا 230 عبوة بلاستيك من الصفوف خلال أسبوع واحد.',
    textEn: 'We collected 230 plastic bottles from classrooms in just one week.',
    likes: 155,
    comments: 24,
    avatar: earthieAvatarUrl,
    icon: '♻️',
    iconBg: '#74cbd5',
    position: { top: '25%', right: '27%' },
    rotation: 5,
    layer: 'front',
    packId: 1,
    density: 'desktop',
  },
  {
    id: 'front-market-bags',
    username: 'نادر',
    usernameEn: 'Nader',
    text: 'وزعنا أكياس قماش في السوق بدل البلاستيك. الناس تفاعلت معنا.',
    textEn: 'We handed out fabric bags at the market instead of plastic. People loved it.',
    likes: 112,
    comments: 17,
    avatar: earthieAvatarUrl,
    icon: '🛍️',
    iconBg: '#bfa7ee',
    position: { top: '63%', left: '23%' },
    rotation: -5,
    layer: 'front',
    packId: 1,
    density: 'desktop',
  },
  {
    id: 'front-group-walk',
    username: 'ميرا',
    usernameEn: 'Mira',
    text: 'مشي جماعي صباح الجمعة بدون سيارات. الجو كان رائع!',
    textEn: 'A group walk on Friday morning with no cars. The weather was amazing!',
    likes: 96,
    comments: 14,
    avatar: earthieAvatarUrl,
    icon: '🌿',
    iconBg: '#4d2d78',
    position: { bottom: '12%', left: '6%' },
    rotation: 4,
    layer: 'front',
    packId: 2,
    density: 'mobile',
  },
  {
    id: 'front-compost-team',
    username: 'شهد',
    usernameEn: 'Shahd',
    text: 'فريق الكومبوست صار عنده 16 مشارك. مين يدخل معنا؟',
    textEn: 'The compost team now has 16 members. Who wants to join us?',
    likes: 101,
    comments: 15,
    avatar: earthieAvatarUrl,
    icon: '🪱',
    iconBg: '#e9a26d',
    position: { bottom: '5%', right: '43%' },
    rotation: 3,
    layer: 'front',
    packId: 3,
    density: 'desktop',
  },
  {
    id: 'front-water-challenge',
    username: 'رنا',
    usernameEn: 'Rana',
    text: 'أنهيت تحدي توفير الماء 5 أيام. إيرثي صار مبسوط!',
    textEn: 'I finished the water-saving challenge for 5 days. Earthie is so happy!',
    likes: 121,
    comments: 19,
    avatar: earthieAvatarUrl,
    icon: '💚',
    iconBg: '#74cbd5',
    position: { bottom: '17%', right: '25%' },
    rotation: -5,
    layer: 'front',
    packId: 3,
    density: 'desktop',
  },
  {
    id: 'front-cup-reuse',
    username: 'جود',
    usernameEn: 'Joud',
    text: 'جبنا أكوابنا معنا اليوم بدل الأكواب البلاستيك. عادة صغيرة وفرق كبير.',
    textEn: 'We brought our own cups today instead of plastic ones. Small habit, big impact.',
    likes: 116,
    comments: 12,
    avatar: earthieAvatarUrl,
    icon: '☕',
    iconBg: '#9de1dd',
    position: { bottom: '8%', right: '16%' },
    rotation: 4,
    layer: 'front',
    packId: 1,
    density: 'desktop',
  },
  {
    id: 'front-bus-team',
    username: 'نور',
    usernameEn: 'Nour',
    text: 'اتفقنا نروح بالباص يومين بالأسبوع ونخفف سيارات قدام المدرسة.',
    textEn: 'We agreed to take the bus twice a week to reduce cars in front of school.',
    likes: 138,
    comments: 18,
    avatar: earthieAvatarUrl,
    icon: '🚌',
    iconBg: '#e96c8f',
    position: { bottom: '1%', right: '18%' },
    rotation: -3,
    layer: 'front',
    packId: 2,
    density: 'desktop',
  },
  {
    id: 'back-lunch-boxes',
    username: 'هيا',
    usernameEn: 'Haya',
    text: 'تحدي علب الطعام القابلة لإعادة الاستخدام بدأ اليوم. مين معنا؟',
    textEn: 'The reusable lunch box challenge started today. Who is with us?',
    likes: 104,
    comments: 13,
    avatar: earthieAvatarUrl,
    icon: '🥗',
    iconBg: '#4d2d78',
    position: { bottom: '10%', right: '31%' },
    rotation: 5,
    layer: 'back',
    packId: 3,
    density: 'desktop',
  },
  {
    id: 'back-phone-right-bottom',
    username: 'سيف',
    usernameEn: 'Saif',
    text: 'ركبنا لوحة تذكير قرب الحنفية: سكّر الماء بعد الاستخدام.',
    textEn: 'We put up a reminder sign near the tap: Turn off water after use.',
    likes: 119,
    comments: 16,
    avatar: earthieAvatarUrl,
    icon: '🚰',
    iconBg: '#9de1dd',
    position: { bottom: '2%', right: '4%' },
    rotation: 3,
    layer: 'back',
    packId: 1,
    density: 'desktop',
  },
]

export const COMMUNITY_PHONE_POSITIONS = {
  'garden-water-saved': { top: '5%', right: '28%' },
  'tree-challenge-started': { top: '10%', right: '8%' },
  'cleanup-progress': { top: '27%', right: '4%' },
  'bike-to-school': { top: '44%', right: '32%' },
  'recycling-bin-alert': { bottom: '15%', right: '23%' },
  'solar-roof-win': { bottom: '6%', right: '5%' },
  'plant-swap': { bottom: '5%', right: '34%' },
  'air-quality-report': { top: '39%', right: '7%' },
  'seed-bank': { top: '18%', right: '34%' },
  'school-points': { top: '57%', right: '30%' },
  'reuse-jars': { bottom: '20%', right: '38%' },
  'lights-off': { top: '3%', right: '38%' },
  'front-compost': { top: '21%', right: '25%' },
  'front-group-photo': { top: '12%', right: '17%' },
  'front-bottle-count': { top: '31%', right: '19%' },
  'front-market-bags': { top: '63%', right: '21%' },
  'front-group-walk': { bottom: '12%', right: '42%' },
  'front-compost-team': { bottom: '5%', right: '27%' },
  'front-water-challenge': { bottom: '20%', right: '13%' },
  'front-cup-reuse': { bottom: '2%', right: '15%' },
  'front-bus-team': { bottom: '12%', right: '2%' },
  'back-lunch-boxes': { bottom: '9%', right: '31%' },
  'back-phone-right-bottom': { bottom: '0%', right: '4%' },
}

export function positionStyle(position, isAr) {
  const nextPosition = isAr
    ? Object.entries(position).reduce((style, [key, value]) => {
      if (key === 'left') {
        style.right = value
        return style
      }

      if (key === 'right') {
        style.left = value
        return style
      }

      style[key] = value
      return style
    }, {})
    : position

  return Object.entries(nextPosition).reduce((style, [key, value]) => {
    style[key] = value
    return style
  }, {})
}
